#! /bin/sh

echo /sbin/firmware.sh > /proc/sys/kernel/hotplug
insmod epl.ko nodeid=1

grep "0" cat /proc/irq/17/netx-eth/threaded > /dev/null

if [ "$?" -ne "0" ] ; then
  echo "WARNING: Ethernet ISR runs as kernel thread!"
  echo "         Please disable CONFIG_PREEMPT_RT in your kernel config."
fi

