#! /bin/sh

modprobe netx-eth
ifup eth0
echo "Checking reachability of NFS server ..."
ping -c 1 192.168.10.45
if [ $? -eq 0 ] ; then
  mount -t nfs -o nolock 192.168.10.45:/projects /mnt/cf
  cd /mnt/cf/EPL_V2/Examples/netx500/Linux/gnu/demo_mn_kernel/
  cp epl.ko ~
fi

