#!/bin/bash
#
# This script creates the standard newlibc/hal Board Support Package (BSP).

BSP_TYPE=hal
BSP_DIR=.

NIOS2_BSP_ARGS="\
--set hal.sys_clk_timer pcp_0_timer_0 \
--cpu-name ${QSYS_SUB}_${QSYS_SUB_CPU} \
--set hal.enable_c_plus_plus false \
--set hal.linker.enable_alt_load_copy_exceptions false \
--set hal.enable_clean_exit false \
--set hal.enable_exit false"

# process arguments
SKIP_MAKE=
while [ $# -gt 0 ]
do
  case "$1" in
      # Don't run make if create-this-app script is called with --no-make arg
      --no-make)
          SKIP_MAKE=1
          ;;
      --rebuild)
          rm -f ./public.mk ./settings.bsp
          ;;
      *)
          NIOS2_BSP_ARGS="$NIOS2_BSP_ARGS $1"
          ;;
  esac
  shift
done

NIOS2_BSP_ARGS="${NIOS2_BSP_ARGS} --set hal.make.bsp_cflags_optimization ${OPT_LEVEL} \
--cmd add_section_mapping .tc_i_mem_pcp $TC_I_MEM"

if [ $DBG_MODE = "NDEBUG" ]; then
NIOS2_BSP_ARGS="${NIOS2_BSP_ARGS} --set hal.stdout none --set hal.stderr none"
fi

# Run nios2-bsp utility to create a hal BSP in this directory
# for the system with a .sopc file in $SOPC_DIR.
cmd="nios2-bsp $BSP_TYPE $BSP_DIR $SOPC_DIR $NIOS2_BSP_ARGS"

echo "create-this-bsp: Running \"$cmd\""
$cmd || {
    echo "$cmd failed"
    exit 1
}

if [ -z "$SKIP_MAKE" ]; then
    echo "create-this-bsp: Running make"
    make
fi
