#!/bin/sh
module="epl"

# invoke rmmod with all arguments we got
/sbin/rmmod $module $* || exit 1

# rebinding network card to ethernet driver
pciid=$(lspci | grep "Intel Corporation 82573" | awk "{printf \"0000:\"\$1}")
echo "rebinding pci device $pciid to network driver"
echo -n $pciid > /sys/bus/pci/drivers/e1000e/bind



