using System;
using System.Runtime.InteropServices;

/// <summary>
/// This file was autogenerated by openCONFIGURATOR-2.0.1_release on 29-Jan-2016 10:38:24
/// Project: Demo_RMN_3CN
/// Application process for openPOWERLINK_MN(240)
/// </summary>

namespace openPOWERLINK
{

	/// <summary>
	/// Struct : ProcessImage Out
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 4)]
	public struct AppProcessImageOut
	{
		[FieldOffset(0)]
		public byte CN01_DigitalInput;
		[FieldOffset(1)]
		public byte CN20_DigitalInput;
		[FieldOffset(2)]
		public byte CN6E_DigitalInput;
		[FieldOffset(3)]
		public byte PADDING_VAR_1;
	}

	/// <summary>
	/// Struct : ProcessImage In
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 4)]
	public struct AppProcessImageIn
	{
		[FieldOffset(0)]
		public byte CN01_DigitalOutput;
		[FieldOffset(1)]
		public byte CN20_DigitalOutput;
		[FieldOffset(2)]
		public byte CN6E_DigitalOutput;
		[FieldOffset(3)]
		public byte PADDING_VAR_1;
	}

}
