using System;
using System.Runtime.InteropServices;

/// <summary>
/// This file was autogenerated by openCONFIGURATOR-2.2.1_release on 11-Jun-2018 17:13:38
/// Project: Demo_RMN_3CN
/// Application process for openPOWERLINK_MN(240)
/// </summary>

namespace openPOWERLINK
{

	/// <summary>
	/// Struct : ProcessImage Out
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 4)]
	public struct AppProcessImageOut
	{
		[FieldOffset(0)]
		public byte CN1_DigitalInput_00h_AU8_DigitalInput;
		[FieldOffset(1)]
		public byte CN32_DigitalInput_00h_AU8_DigitalInput;
		[FieldOffset(2)]
		public byte CN110_DigitalInput_00h_AU8_DigitalInput;
		[FieldOffset(3)]
		public byte PADDING_VAR_1;
	}

	/// <summary>
	/// Struct : ProcessImage In
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 4)]
	public struct AppProcessImageIn
	{
		[FieldOffset(0)]
		public byte CN1_DigitalOutput_00h_AU8_DigitalOutput;
		[FieldOffset(1)]
		public byte CN32_DigitalOutput_00h_AU8_DigitalOutput;
		[FieldOffset(2)]
		public byte CN110_DigitalOutput_00h_AU8_DigitalOutput;
		[FieldOffset(3)]
		public byte PADDING_VAR_1;
	}

}
