/*
* This file was autogenerated by openCONFIGURATOR-2.0.1_release on 29-Jan-2016 10:38:24
* Project: Demo_RMN_3CN
* Application process for openPOWERLINK_MN(240)
*/
#ifndef XAP_h
#define XAP_h

# define COMPUTED_PI_OUT_SIZE 4
typedef struct
{
	unsigned CN01_DigitalInput:8;
	unsigned CN20_DigitalInput:8;
	unsigned CN6E_DigitalInput:8;
	unsigned PADDING_VAR_1:8;
} PI_OUT;

# define COMPUTED_PI_IN_SIZE 4
typedef struct
{
	unsigned CN01_DigitalOutput:8;
	unsigned CN20_DigitalOutput:8;
	unsigned CN6E_DigitalOutput:8;
	unsigned PADDING_VAR_1:8;
} PI_IN;

#endif
