#!/bin/sh
module="epl"

# invoke rmmod with all arguments we got
/sbin/rmmod $module $* || exit 1

# Remove udev rule
rm -f /etc/udev/rules.d/50-openPOWERLINK.rules

# rebinding network card to ethernet driver
pciid=$(lspci | grep RTL-8139 | awk "{printf \"0000:\"\$1}")
echo "rebinding pci device $pciid to network driver"
echo -n $pciid > /sys/bus/pci/drivers/8139too/bind



