#!/bin/sh

echo "check if high resolution timer support is available..."

cat /proc/timer_list | grep 'hres_active.*1' > /dev/null
if [ "$?" -ne "0" ] ; then
  echo
  echo "  High resolution timer support is NOT active."
  echo "  Maybe you need to add 'acpi=force' to kernel command line"
  echo "  or try it on a more recent X86 processor."
  echo
  echo "The EPL module is and will not be loaded!"
  echo
  
  exit
fi


echo "load EPL module: initializing..."

module="epl"

# unbind network card from ethernet driver
pciid=$(lspci | grep RTL-8139 | awk "{printf \"0000:\"\$1}")
echo "unbinding pci device $pciid"
echo -n $pciid > /sys/bus/pci/drivers/8139too/unbind


# install special udev rule, which sets the mode bits appropriately
if [ -d /etc/udev/rules.d ] ; then
    cp 50-openPOWERLINK.rules /etc/udev/rules.d
fi

# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
/sbin/insmod ./$module.ko $* || exit 1


exit 0


