#!/bin/sh
#
# Shell script to set priority of some important kernel threads
#

if [ $USER != "root" ] ; then
  echo "Please run 'sudo $0'"
  exit
fi

echo -n "Check if high resolution timer support is available..."

cat /proc/timer_list | grep 'hres_active.*1' > /dev/null
if [ "$?" -ne "0" ] ; then
  echo "  Failed"
  echo
  echo "  High resolution timer support is NOT active."
  echo "  Maybe you need to add 'acpi=force' to kernel command line"
  echo "  or try it on a more recent X86 processor."
  echo
  echo "The EPL module is and will not be loaded!"
  echo
  
  exit
else
  echo "  OK"
fi

# Set real-time priority openPOWERLINK dependant threads
chrt -f -p 80 `ps -C sirq-hrtimer/0 -o pid --no-headers`
chrt -f -p 80 `ps -C sirq-hrtimer/1 -o pid --no-headers`
chrt -f -p 70 `ps -C \`ps -e -o comm |grep ^irq/.*eth1\$\` -o pid --no-headers` 
chrt -f -p 60 `ps -C sirq-net-rx/0 -o pid --no-headers` 
chrt -f -p 60 `ps -C sirq-net-rx/1 -o pid --no-headers`
exit 0


