# TCL File Generated by Component Editor 9.0
# Fri Aug 07 12:17:06 CEST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | OpenMAC "OpenMAC" v1.0
# |  2009.08.07.12:17:06
# | OpenMAC for Altera Nios II
# | 
# |    OpenMAC_AvalonIF.vhd
# | 
# |    OpenMAC_AvalonIF.vhd syn
# |    OpenMAC_PHYMI.vhd syn
# |    OpenMAC_DMAFifo.vhd syn
# |    OpenMAC_DPR_Altera.vhd syn
# |    OpenMAC.vhd syn
# |    OpenHUB.vhd syn
# |    OpenFILTER.vhd syn
# | 
# +-----------------------------------


# +-----------------------------------
# | module OpenMAC
# | 
set_module_property DESCRIPTION "OpenMAC with OpenHUB and OpenFILTER for Altera Nios II"
set_module_property NAME OpenMAC
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "Interface Protocols/Ethernet"
set_module_property AUTHOR "Bernecker + Rainer"
set_module_property DISPLAY_NAME OpenMAC
set_module_property LIBRARIES {ieee.std_logic_1164.all ieee.std_logic_arith.all ieee.std_logic_unsigned.all std.standard.all}
set_module_property TOP_LEVEL_HDL_FILE OpenMAC_AvalonIF.vhd
set_module_property TOP_LEVEL_HDL_MODULE AlteraOpenMACIF
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file OpenMAC_AvalonIF.vhd SYNTHESIS
add_file OpenMAC_PHYMI.vhd SYNTHESIS
add_file OpenMAC_DMAFifo.vhd SYNTHESIS
add_file OpenMAC_DPR_Altera.vhd SYNTHESIS
add_file OpenMAC.vhd SYNTHESIS
add_file OpenHUB.vhd SYNTHESIS
add_file OpenFILTER.vhd SYNTHESIS
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter MacTimer BOOLEAN true
set_parameter_property MacTimer DISPLAY_NAME MacTimer
set_parameter_property MacTimer UNITS None
set_parameter_property MacTimer DISPLAY_HINT "Enables a 32bit Timer to generate IRQ"
set_parameter_property MacTimer AFFECTS_GENERATION false
set_parameter_property MacTimer IS_HDL_PARAMETER true
add_parameter Simulate BOOLEAN false
set_parameter_property Simulate DISPLAY_NAME Simulate
set_parameter_property Simulate UNITS None
set_parameter_property Simulate DISPLAY_HINT "Should be set in case of simulation"
set_parameter_property Simulate AFFECTS_GENERATION false
set_parameter_property Simulate IS_HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk_sink
# | 
add_interface clk_sink clock end
set_interface_property clk_sink ptfSchematicName ""

set_interface_property clk_sink ENABLED true

add_interface_port clk_sink Clk clk Input 1
add_interface_port clk_sink Reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point Mii
# | 
add_interface Mii avalon end
set_interface_property Mii addressAlignment DYNAMIC
set_interface_property Mii bridgesToMaster ""
set_interface_property Mii burstOnBurstBoundariesOnly false
set_interface_property Mii holdTime 0
set_interface_property Mii isMemoryDevice false
set_interface_property Mii isNonVolatileStorage false
set_interface_property Mii linewrapBursts false
set_interface_property Mii maximumPendingReadTransactions 0
set_interface_property Mii printableDevice false
set_interface_property Mii readLatency 0
set_interface_property Mii readWaitStates 0
set_interface_property Mii readWaitTime 0
set_interface_property Mii setupTime 0
set_interface_property Mii timingUnits Cycles
set_interface_property Mii writeWaitTime 1

set_interface_property Mii ASSOCIATED_CLOCK clk_sink
set_interface_property Mii ENABLED true

add_interface_port Mii mii_Addr address Input 3
add_interface_port Mii mii_Sel chipselect Input 1
add_interface_port Mii mii_nBe byteenable_n Input 2
add_interface_port Mii mii_nWr write_n Input 1
add_interface_port Mii mii_Data_In writedata Input 16
add_interface_port Mii mii_Data_Out readdata Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point portSMI
# | 
add_interface portSMI conduit end

set_interface_property portSMI ENABLED true

add_interface_port portSMI mii_Clk export Output 1
add_interface_port portSMI mii_Di export Input 1
add_interface_port portSMI mii_Do export Output 1
add_interface_port portSMI mii_Doe export Output 1
add_interface_port portSMI mii_nResetOut export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point DMA
# | 
add_interface DMA avalon start
set_interface_property DMA adaptsTo ""
set_interface_property DMA burstOnBurstBoundariesOnly false
set_interface_property DMA doStreamReads false
set_interface_property DMA doStreamWrites false
set_interface_property DMA linewrapBursts false

set_interface_property DMA ASSOCIATED_CLOCK clk_sink
set_interface_property DMA ENABLED true

add_interface_port DMA m_read_n read_n Output 1
add_interface_port DMA m_write_n write_n Output 1
add_interface_port DMA m_byteenable_n byteenable_n Output 2
add_interface_port DMA m_address address Output 32
add_interface_port DMA m_writedata writedata Output 16
add_interface_port DMA m_readdata readdata Input 16
add_interface_port DMA m_waitrequest waitrequest Input 1
add_interface_port DMA m_arbiterlock arbiterlock Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point RX
# | 
add_interface RX avalon end
set_interface_property RX addressAlignment DYNAMIC
set_interface_property RX bridgesToMaster ""
set_interface_property RX burstOnBurstBoundariesOnly false
set_interface_property RX holdTime 0
set_interface_property RX isMemoryDevice false
set_interface_property RX isNonVolatileStorage false
set_interface_property RX linewrapBursts false
set_interface_property RX maximumPendingReadTransactions 0
set_interface_property RX printableDevice false
set_interface_property RX readLatency 0
set_interface_property RX readWaitTime 1
set_interface_property RX setupTime 0
set_interface_property RX timingUnits Cycles
set_interface_property RX writeWaitStates 1
set_interface_property RX writeWaitTime 1

set_interface_property RX ASSOCIATED_CLOCK clk_sink
set_interface_property RX ENABLED true

add_interface_port RX d_chipselect chipselect Input 1
add_interface_port RX d_read_n read_n Input 1
add_interface_port RX d_write_n write_n Input 1
add_interface_port RX d_byteenable byteenable Input 2
add_interface_port RX d_address address Input 1
add_interface_port RX d_writedata writedata Input 16
add_interface_port RX d_readdata readdata Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point REG
# | 
add_interface REG avalon end
set_interface_property REG addressAlignment DYNAMIC
set_interface_property REG bridgesToMaster ""
set_interface_property REG burstOnBurstBoundariesOnly false
set_interface_property REG holdTime 0
set_interface_property REG isMemoryDevice false
set_interface_property REG isNonVolatileStorage false
set_interface_property REG linewrapBursts false
set_interface_property REG maximumPendingReadTransactions 0
set_interface_property REG printableDevice false
set_interface_property REG readLatency 0
set_interface_property REG readWaitTime 1
set_interface_property REG setupTime 0
set_interface_property REG timingUnits Cycles
set_interface_property REG writeWaitStates 0
set_interface_property REG writeWaitTime 0

set_interface_property REG ASSOCIATED_CLOCK clk_sink
set_interface_property REG ENABLED true

add_interface_port REG chipselect chipselect Input 1
add_interface_port REG read_n read_n Input 1
add_interface_port REG write_n write_n Input 1
add_interface_port REG byteenable byteenable_n Input 2
add_interface_port REG address address Input 11
add_interface_port REG writedata writedata Input 16
add_interface_port REG readdata readdata Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point TimerCmp
# | 
add_interface TimerCmp avalon end
set_interface_property TimerCmp addressAlignment DYNAMIC
set_interface_property TimerCmp bridgesToMaster ""
set_interface_property TimerCmp burstOnBurstBoundariesOnly false
set_interface_property TimerCmp holdTime 0
set_interface_property TimerCmp isMemoryDevice false
set_interface_property TimerCmp isNonVolatileStorage false
set_interface_property TimerCmp linewrapBursts false
set_interface_property TimerCmp maximumPendingReadTransactions 0
set_interface_property TimerCmp printableDevice false
set_interface_property TimerCmp readLatency 0
set_interface_property TimerCmp readWaitTime 1
set_interface_property TimerCmp setupTime 0
set_interface_property TimerCmp timingUnits Cycles
set_interface_property TimerCmp writeWaitStates 0
set_interface_property TimerCmp writeWaitTime 0

set_interface_property TimerCmp ASSOCIATED_CLOCK clk_sink
set_interface_property TimerCmp ENABLED true

add_interface_port TimerCmp t_chipselect chipselect Input 1
add_interface_port TimerCmp t_read_n read_n Input 1
add_interface_port TimerCmp t_write_n write_n Input 1
add_interface_port TimerCmp t_byteenable byteenable Input 4
add_interface_port TimerCmp t_address address Input 1
add_interface_port TimerCmp t_writedata writedata Input 32
add_interface_port TimerCmp t_readdata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interruptRX
# | 
add_interface interruptRX interrupt end
set_interface_property interruptRX associatedAddressablePoint RX

set_interface_property interruptRX ASSOCIATED_CLOCK clk_sink
set_interface_property interruptRX ENABLED true

add_interface_port interruptRX nRx_Int irq_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interruptTX
# | 
add_interface interruptTX interrupt end
set_interface_property interruptTX associatedAddressablePoint REG

set_interface_property interruptTX ASSOCIATED_CLOCK clk_sink
set_interface_property interruptTX ENABLED true

add_interface_port interruptTX nTx_Int irq_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interruptCMP
# | 
add_interface interruptCMP interrupt end
set_interface_property interruptCMP associatedAddressablePoint TimerCmp

set_interface_property interruptCMP ASSOCIATED_CLOCK clk_sink
set_interface_property interruptCMP ENABLED true

add_interface_port interruptCMP nCmp_Int irq_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point RMII0
# | 
add_interface RMII0 conduit end

set_interface_property RMII0 ASSOCIATED_CLOCK clk_sink
set_interface_property RMII0 ENABLED true

add_interface_port RMII0 rCrs_Dv_0 export Input 1
add_interface_port RMII0 rTx_Dat_0 export Output 2
add_interface_port RMII0 rTx_En_0 export Output 1
add_interface_port RMII0 rRx_Dat_0 export Input 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point RMII1
# | 
add_interface RMII1 conduit end

set_interface_property RMII1 ASSOCIATED_CLOCK clk_sink
set_interface_property RMII1 ENABLED true

add_interface_port RMII1 rCrs_Dv_1 export Input 1
add_interface_port RMII1 rTx_Dat_1 export Output 2
add_interface_port RMII1 rTx_En_1 export Output 1
add_interface_port RMII1 rRx_Dat_1 export Input 2
# | 
# +-----------------------------------
