#!/bin/sh
# This script does the following steps:
#  1. Generate the Qsys design
#  2. Compile the Quartus II design
# Note: Write into console "$ export QUARTUS_SKIP=1" to skip Quartus flow

# Quartus Project name
QUARTUS_PRJ=ink_de2-115

# Qsys toplevel name
QSYS_PRJ=mn_par_host

ip-generate --outputdirectory=${QSYS_PRJ}/synthesis/ \
            --file-set=QUARTUS_SYNTH \
            --reportfile=sopcinfo:${QSYS_PRJ}.sopcinfo \
            --reportfile=html:${QSYS_PRJ}.html \
            --reportfile=qip:${QSYS_PRJ}/synthesis/${QSYS_PRJ}.qip \
            --component-file=${QSYS_PRJ}.qsys

#check return
if [ $? -ne 0 ]; then
    exit 1
fi

# Do Quartus flow if skip variable is empty
if [ -z "${QUARTUS_SKIP}" ];
then
    #Workaround: Remove done file
    if [ -f ${QUARTUS_PRJ}.done ]
    then
        rm ${QUARTUS_PRJ}.done
    fi

    quartus_cmd ${QUARTUS_PRJ}.qpf -c ${QUARTUS_PRJ}.qsf

    #Workaround: Quartus returned unsuccessful if done file doesn't exist
    if [ ! -f ${QUARTUS_PRJ}.done ]
    then
        echo "Failed!"
        exit 1
    fi
else
    echo "INFO: Skipped Quartus compilation flow!"
fi

exit 0
