/* This file was autogenerated by openCONFIGURATOR-1.2.1 on 01-Feb-2013 18:23:47 */
# define COMPUTED_PI_OUT_SIZE 12
typedef struct 
{
	unsigned CN1_M00_Digital_Input_8_Bit_Byte_1:8;
	unsigned CN2_M00_Digital_Input_8_Bit_Byte_1:8;
	unsigned CN3_M00_Digital_Input_8_Bit_Byte_1:8;
	unsigned CN4_M00_Digital_Input_8_Bit_Byte_1:8;
	unsigned CN5_M00_Digital_Input_8_Bit_Byte_1:8;
	unsigned CN6_M00_Digital_Input_8_Bit_Byte_1:8;
	unsigned CN7_M00_Digital_Input_8_Bit_Byte_1:8;
	unsigned CN8_M00_Digital_Input_8_Bit_Byte_1:8;
	unsigned CN9_M00_Digital_Input_8_Bit_Byte_1:8;
	unsigned CN10_M00_Digital_Input_8_Bit_Byte_1:8;
	unsigned CN11_M00_Digital_Input_8_Bit_Byte_1:8;
	unsigned CN12_M00_Digital_Input_8_Bit_Byte_1:8;
} PI_OUT;

# define COMPUTED_PI_IN_SIZE 12
typedef struct 
{
	unsigned CN1_M00_Digital_Ouput_8_Bit_Byte_1:8;
	unsigned CN2_M00_Digital_Ouput_8_Bit_Byte_1:8;
	unsigned CN3_M00_Digital_Ouput_8_Bit_Byte_1:8;
	unsigned CN4_M00_Digital_Ouput_8_Bit_Byte_1:8;
	unsigned CN5_M00_Digital_Ouput_8_Bit_Byte_1:8;
	unsigned CN6_M00_Digital_Ouput_8_Bit_Byte_1:8;
	unsigned CN7_M00_Digital_Ouput_8_Bit_Byte_1:8;
	unsigned CN8_M00_Digital_Ouput_8_Bit_Byte_1:8;
	unsigned CN9_M00_Digital_Ouput_8_Bit_Byte_1:8;
	unsigned CN10_M00_Digital_Ouput_8_Bit_Byte_1:8;
	unsigned CN11_M00_Digital_Ouput_8_Bit_Byte_1:8;
	unsigned CN12_M00_Digital_Ouput_8_Bit_Byte_1:8;
} PI_IN;
