/* This file was autogenerated by openCONFIGURATOR-1.4.0 on 20-Jan-2015 09:30:21 */
#ifndef XAP_h
#define XAP_h

# define COMPUTED_PI_OUT_SIZE 4
typedef struct 
{
	unsigned CN1_M00_DigitalInput_00h_AU8_DigitalInput:8;
	unsigned CN32_M00_DigitalInput_00h_AU8_DigitalInput:8;
	unsigned CN110_M00_DigitalInput_00h_AU8_DigitalInput:8;
	unsigned PADDING_VAR_1:8;
} PI_OUT;

# define COMPUTED_PI_IN_SIZE 4
typedef struct 
{
	unsigned CN1_M00_DigitalOutput_00h_AU8_DigitalOutput:8;
	unsigned CN32_M00_DigitalOutput_00h_AU8_DigitalOutput:8;
	unsigned CN110_M00_DigitalOutput_00h_AU8_DigitalOutput:8;
	unsigned PADDING_VAR_1:8;
} PI_IN;

#endif
